desc 'recreate sprite sheets'
task 'resprite' do
  require 'sprite_factory'

  input_dir  = 'images/sprites'
  output_dir = 'images'

  validate_directory(input_dir)
  validate_directory(output_dir)

  start_time = Time.now

  images = SpriteFactory.run!(input_dir, layout: :packed, output_style: "#{output_dir}/sprites.js", margin: 5, nocomments: true) do |images|
    SpriteHelper.javascript_style("SPRITES", images)
  end

  print_sprite_sheet_stats(images, "#{output_dir}/sprites.js", start_time)

  images = SpriteFactory.run!(input_dir: 'images/background', layout: :vertical, output_style: "#{output_dir}/background.js", margin: 5, nocomments: true) do |images|
    SpriteHelper.javascript_style("BACKGROUND", images)
  end

  print_sprite_sheet_stats(images, "#{output_dir}/background.js", start_time)
end

#------------------------------------------------------------------------------

module SpriteHelper
  def self.javascript_style(variable, images)
    maxname = images.keys.inject(0) { |n, key| [n, key.length].max }
    rules = []
    images.each do |name, i|
      name      
