// Game Events
export const GAME_START_NOW = 'GAME_START_NOW'
export const GAME_USER_OPTION = 'GAME_USER_OPTION'
export const HOOK_DOWN = 'HOOK_DOWN'
export const HOOK_UP = 'HOOK_UP'
export const HOOK_NORMAL = 'HOOK_NORMAL'
export const ROTATE_RIGHT = 'ROTATE_RIGHT'
export const ROTATE_LEFT = 'ROTATE_LEFT'
export const SWING = 'SWING'
export const BEFORE_DROP = 'BEFORE_DROP'
export const DROP = 'DROP'
export const LAND = 'LAND'
export const OUT = 'OUT'

// Game Scores
export const SUCCESS_COUNT = 'SUCCESS_COUNT'
export const FAILED_COUNT = 'FAILED_COUNT'
export const PERFECT_COUNT = 'PERFECT_COUNT'
export const GAME_SCORE = 'GAME_SCORE'

// Game Animations
export const BG_INIT_MOVEMENT = 'BG_INIT_MOVEMENT'
export const HOOK_DOWN_MOVEMENT = 'HOOK_DOWN_MOVEMENT'
export const HOOK_UP_MOVEMENT = 'HOOK_UP_MOVEMENT'
export const LIGHTNING_MOVEMENT = 'LIGHTNING_MOVEMENT'
export const TUTORIAL_MOVEMENT = 'TUTORIAL_MOVEMENT'
export const MOVE_DOWN_MOVEMENT = 'MOVE_DOWN_MOVEMENT'

// Game Layout
export const HARD_MODE = 'HARD_MODE'
export const BACKGROUND_IMG_OFFSET_HEIGHT = 'BACKGROUND_IMG_OFFSET_HEIGHT'
export const LINE_INITIAL_OFFSET = 'LINE_INITIAL_OFFSET'
export const BACKGROUND_LINEAR_GRADIENT_OFFSET_HEIGHT = 'BACKGROUND_LINEAR_GRADIENT_OFFSET_HEIGHT'

// Game Blocks
export const BLOCK_COUNT = 'BLOCK_COUNT'
export const BLOCK_WIDTH = 'BLOCK_WIDTH'
export const BLOCK_HEIGHT = 'BLOCK_HEIGHT'
export const CLOUD_SIZE = 'CLOUD_SIZE'
export const ROPE_HEIGHT = 'ROPE_HEIGHT'
export const FLIGHT_COUNT = 'FLIGHT_COUNT'
export const FLIGHT_LAYER = 'FLIGHT_LAYER
