// The current version of the project or application
const version = "6";  // number or string indicating the version

// An array of library objects, where each object contains the name and version of a library
const libs = [
  { name: "phaser-ads", version: "2.2" },  // Phaser Ads library
  { name: "phaser-cachebuster", version: "2.0" },  // Phaser Cachebuster library
  { name: "phaser-input", version: "2.0" },  // Phaser Input library
  { name: "phaser-nineslice", version: "2.0" },  // Phaser NineSlice library
  { name: "phaser-spine", version: "3.0" },  // Phaser Spine library
  { name: "phaser-super-storage", version: "1.0" },  // Phaser Super Storage library
  { name: "splash", version: "3.5" },  // Splash library
];

// The base URL for accessing the libraries via JSDelivr CDN
const baseUrl = "https://cdn.jsdelivr.net/npm/@orange-games/";  // base URL for library CDN

// An array of library URLs generated by mapping the 'libs' array to the desired URL format
const libUrls = libs.map(lib => `${baseUrl}${lib.name}@${lib.version}/build/${lib.name}.min.js` );

// Log the version and library URLs to the console
console.log("version:", version);  // Log the version number
console.log("libraries:", libUrls);  // Log the array of library URLs

